# Generated by Django 4.2.3 on 2023-07-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_add',
        ),
    ]
