# Generated by Django 4.2.3 on 2023-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_remove_recipe_author_remove_recipe_time_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.TextField(default='Description coming soon', max_length=10000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
